#!/bin/bash

#To replace the quill with the forked version

degit --force quire-io/quill node_modules/quill-fork

cd node_modules/quill-fork
npm install
npm run build:quill

rsync -av --delete ./packages/quill/dist/ ../quill/

cd ..
rm -rf quill-fork